import { Transaction, ProcessedTransaction, ExportOptions } from '../types';
import { CURRENCIES } from '../constants';

/**
 * Generate CSV from transactions
 */
export const generateCSV = (transactions: ProcessedTransaction[], currency: string): string => {
  const headers = ['Date', 'Merchant', 'Category', 'Type', 'Amount', 'Currency', 'Wallet', 'Tags', 'Notes'];
  
  const rows = transactions.map(t => [
    t.date,
    t.displayMerchant,
    t.displayCategory,
    t.type,
    t.amount.toFixed(2),
    t.currency,
    t.walletId || '-',
    t.tags?.join('; ') || '-',
    t.notes || '-'
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');

  return csvContent;
};

/**
 * Download CSV file
 */
export const downloadCSV = (csvContent: string, filename: string = 'expenwall-export.csv') => {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

/**
 * Generate PDF report (requires jsPDF library)
 */
export const generatePDF = async (
  transactions: ProcessedTransaction[],
  options: {
    currency: string;
    dateFrom: string;
    dateTo: string;
    totalIncome: number;
    totalExpense: number;
    netBalance: number;
  }
) => {
  // Use dynamic imports that resolve to the CDN versions in importmap
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF();
  const currencySymbol = CURRENCIES.find(c => c.code === options.currency)?.symbol || '$';

  // Title
  doc.setFontSize(20);
  doc.setTextColor(99, 102, 241); // Indigo
  doc.text('Expenwall Report', 14, 20);

  // Period
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Period: ${options.dateFrom} to ${options.dateTo}`, 14, 28);

  // Summary Box
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Income: ${currencySymbol}${options.totalIncome.toFixed(2)}`, 14, 38);
  doc.text(`Total Expense: ${currencySymbol}${options.totalExpense.toFixed(2)}`, 14, 45);
  doc.text(`Net Balance: ${currencySymbol}${options.netBalance.toFixed(2)}`, 14, 52);

  // Transactions Table
  const tableData = transactions.map(t => [
    t.date,
    t.displayMerchant,
    t.displayCategory,
    t.type,
    `${currencySymbol}${t.amount.toFixed(2)}`
  ]);

  autoTable(doc, {
    startY: 60,
    head: [['Date', 'Merchant', 'Category', 'Type', 'Amount']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 8 },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by Expenwall - Page ${pageCount}`, 14, doc.internal.pageSize.height - 10);

  // Save
  doc.save(`expenwall-report-${options.dateFrom}-to-${options.dateTo}.pdf`);
};