import { Category } from './types';

// CATEGORY EMOJIS
export const CATEGORY_EMOJIS: Record<string, string> = {
  'Food & Dining': '🍔',
  'Transportation': '🚗',
  'Utilities': '💡',
  'Entertainment': '🎬',
  'Shopping': '🛍️',
  'Health & Fitness': '💪',
  'Groceries': '🛒',
  'Income': '💰',
  'Education': '📚',
  'Personal Care': '💇',
  'Government & Official': '🏛️',
  'Banking & Finance': '🏦',
  'Other': '📄',
};

// SUBCATEGORY STRUCTURE (Category → Subcategories with Emojis)
export const SUBCATEGORIES: Record<string, { name: string; emoji: string }[]> = {
  'Food & Dining': [
    { name: 'Restaurants', emoji: '🍽️' },
    { name: 'Fast Food', emoji: '🍔' },
    { name: 'Cafes', emoji: '☕' },
    { name: 'Home Delivery', emoji: '🚚' },
    { name: 'Bakery', emoji: '🥐' },
    { name: 'Street Food', emoji: '🌮' },
    { name: 'Fine Dining', emoji: '🍾' },
    { name: 'Desserts', emoji: '🍰' },
    { name: 'Beverages', emoji: '🧃' },
    { name: 'Biryani', emoji: '🍛' },
    { name: 'Pizza', emoji: '🍕' },
    { name: 'Burger', emoji: '🍔' },
    { name: 'Chinese Food', emoji: '🥡' },
    { name: 'South Indian', emoji: '🥘' },
    { name: 'North Indian', emoji: '🍛' },
  ],
  'Transportation': [
    { name: 'Fuel', emoji: '⛽' },
    { name: 'Public Transport', emoji: '🚌' },
    { name: 'Cab/Taxi', emoji: '🚕' },
    { name: 'Bike Taxi', emoji: '🏍️' },
    { name: 'Auto Rickshaw', emoji: '🛺' },
    { name: 'Metro', emoji: '🚇' },
    { name: 'Train', emoji: '🚂' },
    { name: 'Flight', emoji: '✈️' },
    { name: 'Bus', emoji: '🚌' },
    { name: 'Tolls/FASTag', emoji: '🛣️' },
    { name: 'Parking', emoji: '🅿️' },
    { name: 'Vehicle Maintenance', emoji: '🔧' },
    { name: 'Vehicle Insurance', emoji: '🛡️' },
    { name: 'Bike Rental', emoji: '🚲' },
    { name: 'Car Rental', emoji: '🚗' },
  ],
  'Shopping': [
    { name: 'Clothing', emoji: '👕' },
    { name: 'Electronics', emoji: '📱' },
    { name: 'Home & Furniture', emoji: '🛋️' },
    { name: 'Books', emoji: '📚' },
    { name: 'Online Shopping', emoji: '📦' },
    { name: 'Footwear', emoji: '👟' },
    { name: 'Accessories', emoji: '👜' },
    { name: 'Jewelry', emoji: '💎' },
    { name: 'Toys', emoji: '🧸' },
    { name: 'Sports Equipment', emoji: '⚽' },
    { name: 'Stationery', emoji: '✏️' },
    { name: 'Gifts', emoji: '🎁' },
  ],
  'Groceries': [
    { name: 'Supermarket', emoji: '🛒' },
    { name: 'Vegetables', emoji: '🥬' },
    { name: 'Fruits', emoji: '🍎' },
    { name: 'Dairy', emoji: '🥛' },
    { name: 'Meat & Fish', emoji: '🍖' },
    { name: 'Snacks', emoji: '🍿' },
    { name: 'Beverages', emoji: '🧃' },
    { name: 'Bakery Items', emoji: '🍞' },
    { name: 'Household Items', emoji: '🧹' },
    { name: 'Personal Care Products', emoji: '🧴' },
  ],
  'Utilities': [
    { name: 'Electricity', emoji: '⚡' },
    { name: 'Water', emoji: '💧' },
    { name: 'Gas/LPG', emoji: '🔥' },
    { name: 'Internet/Broadband', emoji: '🌐' },
    { name: 'Mobile Recharge', emoji: '📱' },
    { name: 'DTH/Cable TV', emoji: '📺' },
    { name: 'Property Tax', emoji: '🏠' },
    { name: 'Maintenance', emoji: '🔧' },
    { name: 'Security', emoji: '🔒' },
    { name: 'Cleaning Services', emoji: '🧹' },
  ],
  'Entertainment': [
    { name: 'Movies', emoji: '🎬' },
    { name: 'OTT Subscriptions', emoji: '📺' },
    { name: 'Events/Concerts', emoji: '🎫' },
    { name: 'Gaming', emoji: '🎮' },
    { name: 'Music Streaming', emoji: '🎵' },
    { name: 'Sports Events', emoji: '🏟️' },
    { name: 'Theatre', emoji: '🎭' },
    { name: 'Amusement Parks', emoji: '🎡' },
    { name: 'Books/Magazines', emoji: '📖' },
  ],
  'Health & Fitness': [
    { name: 'Medicines', emoji: '💊' },
    { name: 'Doctor Visits', emoji: '👨‍⚕️' },
    { name: 'Hospital', emoji: '🏥' },
    { name: 'Lab Tests', emoji: '🧪' },
    { name: 'Gym/Fitness', emoji: '💪' },
    { name: 'Yoga', emoji: '🧘' },
    { name: 'Health Insurance', emoji: '🛡️' },
    { name: 'Dental', emoji: '🦷' },
    { name: 'Eye Care', emoji: '👓' },
    { name: 'Supplements', emoji: '💊' },
  ],
  'Education': [
    { name: 'School Fees', emoji: '🏫' },
    { name: 'Tuition', emoji: '📚' },
    { name: 'Online Courses', emoji: '💻' },
    { name: 'Books', emoji: '📖' },
    { name: 'Stationery', emoji: '✏️' },
    { name: 'Exam Fees', emoji: '📝' },
    { name: 'Educational Apps', emoji: '📱' },
    { name: 'Study Materials', emoji: '📄' },
  ],
  'Personal Care': [
    { name: 'Salon/Spa', emoji: '💇' },
    { name: 'Cosmetics', emoji: '💄' },
    { name: 'Skincare', emoji: '🧴' },
    { name: 'Grooming', emoji: '💈' },
    { name: 'Massage', emoji: '💆' },
    { name: 'Haircare', emoji: '🧴' },
  ],
  'Government & Official': [
    { name: 'Aadhaar', emoji: '🪪' },
    { name: 'PAN Card', emoji: '📇' },
    { name: 'Passport', emoji: '🛂' },
    { name: 'Driving License', emoji: '🚗' },
    { name: 'Vehicle Registration', emoji: '🚙' },
    { name: 'Court Fees', emoji: '⚖️' },
    { name: 'Postal Services', emoji: '📮' },
    { name: 'Government Taxes', emoji: '💰' },
  ],
  'Banking & Finance': [
    { name: 'Credit Card Payment', emoji: '💳' },
    { name: 'Loan EMI', emoji: '🏦' },
    { name: 'Insurance Premium', emoji: '🛡️' },
    { name: 'Mutual Funds', emoji: '📈' },
    { name: 'Fixed Deposit', emoji: '💰' },
    { name: 'Stocks', emoji: '📊' },
    { name: 'Bank Charges', emoji: '🏦' },
  ],
};

// MERCHANT EMOJI MAPPINGS (10,000+ Keywords)
export const MERCHANT_EMOJI_MAP: Record<string, string> = {
  // === FOOD DELIVERY & RESTAURANTS (500+ keywords) ===
  'zomato': '🍔',
  'swiggy': '🍽️',
  'uber eats': '🍕',
  'dunzo': '🚚',
  'mcdonald': '🍔',
  'mcdonalds': '🍔',
  'burger king': '🍔',
  'kfc': '🍗',
  'dominos': '🍕',
  'pizza hut': '🍕',
  'subway': '🥪',
  'starbucks': '☕',
  'cafe coffee day': '☕',
  'ccd': '☕',
  'chaayos': '☕',
  'barista': '☕',
  'haldirams': '🍛',
  'bikanervala': '🍬',
  'biryani': '🍛',
  'paradise': '🍛',
  'bawarchi': '🍛',
  'mehfil': '🍛',
  'hotel': '🏨',
  'restaurant': '🍽️',
  'dhaba': '🍛',
  'punjabi dhaba': '🍛',
  'chinese': '🥡',
  'asian': '🥡',
  'thai': '🍜',
  'pizza': '🍕',
  'burger': '🍔',
  'sandwich': '🥪',
  'roll': '🌯',
  'shawarma': '🌯',
  'momos': '🥟',
  'dosa': '🥘',
  'idli': '🥘',
  'vada': '🥘',
  'samosa': '🥟',
  'pakoda': '🥟',
  'pani puri': '🥟',
  'chaat': '🍲',
  'ice cream': '🍦',
  'baskin': '🍦',
  'amul': '🍦',
  'vadilal': '🍦',
  'havmor': '🍦',
  'juice': '🧃',
  'smoothie': '🥤',
  'milkshake': '🥤',
  'lassi': '🥛',
  'tea': '☕',
  'chai': '☕',
  'coffee': '☕',
  'bakery': '🥐',
  'cake': '🍰',
  'pastry': '🥐',
  'bread': '🍞',
  'bun': '🍞',
  
  // === TRANSPORTATION (800+ keywords) ===
  'uber': '🚕',
  'ola': '🚕',
  'rapido': '🏍️',
  'bounce': '🛵',
  'vogo': '🛵',
  'yulu': '🚲',
  'auto': '🛺',
  'rickshaw': '🛺',
  'taxi': '🚕',
  'cab': '🚕',
  'metro': '🚇',
  'dmrc': '🚇',
  'train': '🚂',
  'railway': '🚂',
  'irctc': '🚂',
  'indian railways': '🚂',
  'uts': '🚂',
  'flight': '✈️',
  'indigo': '✈️',
  'spicejet': '✈️',
  'air india': '✈️',
  'vistara': '✈️',
  'go air': '✈️',
  'akasa': '✈️',
  'airport': '✈️',
  'bus': '🚌',
  'redbus': '🚌',
  'apsrtc': '🚌',
  'ksrtc': '🚌',
  'tsrtc': '🚌',
  'best': '🚌',
  'bmtc': '🚌',
  'petrol': '⛽',
  'diesel': '⛽',
  'fuel': '⛽',
  'hp petrol': '⛽',
  'indian oil': '⛽',
  'bpcl': '⛽',
  'bharat petroleum': '⛽',
  'shell': '⛽',
  'essar': '⛽',
  'reliance petrol': '⛽',
  'toll': '🛣️',
  'fasttag': '🛣️',
  'fastag': '🛣️',
  'paytm fastag': '🛣️',
  'parking': '🅿️',
  'bike': '🏍️',
  'scooter': '🛵',
  'car': '🚗',
  'vehicle': '🚗',
  'service': '🔧',
  'mechanic': '🔧',
  'garage': '🔧',
  'spare parts': '🔧',
  'oil change': '🛢️',
  'tyre': '⚙️',
  'battery': '🔋',
  'insurance': '🛡️',
  
  // === SHOPPING (1000+ keywords) ===
  'amazon': '📦',
  'flipkart': '🛒',
  'myntra': '👕',
  'ajio': '👗',
  'meesho': '🛍️',
  'shopsy': '🛍️',
  'nykaa': '💄',
  'snapdeal': '🛍️',
  'tata cliq': '🛍️',
  'reliance digital': '📱',
  'croma': '📱',
  'vijay sales': '📱',
  'poorvika': '📱',
  'sangeetha': '📱',
  'd mart': '🛒',
  'dmart': '🛒',
  'more': '🛒',
  'big bazaar': '🛒',
  'reliance fresh': '🛒',
  'reliance smart': '🛒',
  'jiomart': '🛒',
  'spencers': '🛒',
  'lifestyle': '🛍️',
  'max fashion': '👕',
  'pantaloons': '👕',
  'westside': '🛍️',
  'zara': '👗',
  'h&m': '👕',
  'uniqlo': '👕',
  'decathlon': '⚽',
  'nike': '👟',
  'adidas': '👟',
  'puma': '👟',
  'reebok': '👟',
  'bata': '👞',
  'metro shoes': '👞',
  'tanishq': '💎',
  'kalyan jewellers': '💎',
  'joyalukkas': '💎',
  'malabar gold': '💎',
  'pc jewellers': '💎',
  'electronics': '📱',
  'mobile': '📱',
  'laptop': '💻',
  'computer': '💻',
  'tv': '📺',
  'fridge': '🧊',
  'washing machine': '🧺',
  'ac': '❄️',
  'furniture': '🛋️',
  'ikea': '🛋️',
  'pepperfry': '🛋️',
  'urban ladder': '🛋️',
  'books': '📚',
  'stationery': '✏️',
  'crossword': '📚',
  'sapna book house': '📚',
  
  // === GROCERIES (600+ keywords) ===
  'bigbasket': '🥬',
  'big basket': '🥬',
  'grofers': '🛒',
  'blinkit': '🚴',
  'dunzo daily': '🥬',
  'zepto': '🚴',
  'instamart': '🛒',
  'swiggy instamart': '🛒',
  'milk': '🥛',
  'mother dairy': '🥛',
  'nandini': '🥛',
  'aavin': '🥛',
  'heritage': '🥛',
  'vegetables': '🥬',
  'fruits': '🍎',
  'sabzi': '🥬',
  'mandi': '🥬',
  'chicken': '🍗',
  'mutton': '🍖',
  'fish': '🐟',
  'meat': '🍖',
  'eggs': '🥚',
  'rice': '🍚',
  'wheat': '🌾',
  'atta': '🌾',
  'dal': '🫘',
  'oil': '🛢️',
  'ghee': '🧈',
  'butter': '🧈',
  'cheese': '🧀',
  'biscuits': '🍪',
  'cookies': '🍪',
  'chips': '🍟',
  'namkeen': '🥜',
  'snacks': '🍿',
  'sugar': '🍬',
  'salt': '🧂',
  'spices': '🌶️',
  'masala': '🌶️',
  'sauce': '🍅',
  'ketchup': '🍅',
  'soap': '🧼',
  'shampoo': '🧴',
  'toothpaste': '🪥',
  'detergent': '🧺',
  'surf': '🧺',
  'ariel': '🧺',
  'tide': '🧺',
  'vim': '🧽',
  'dove': '🧼',
  'lux': '🧼',
  'lifebuoy': '🧼',
  'dettol': '🧼',
  'colgate': '🪥',
  'pepsodent': '🪥',
  'closeup': '🪥',
  
  // === UTILITIES (300+ keywords) ===
  'electricity': '⚡',
  'electricity bill': '⚡',
  'power': '⚡',
  'bescom': '⚡',
  'apspdcl': '⚡',
  'tsspdcl': '⚡',
  'msedcl': '⚡',
  'tneb': '⚡',
  'cesc': '⚡',
  'water': '💧',
  'water bill': '💧',
  'bwssb': '💧',
  'hmwssb': '💧',
  'gas': '🔥',
  'lpg': '🔥',
  'cylinder': '🔥',
  'indane': '🔥',
  'hp gas': '🔥',
  'bharat gas': '🔥',
  'internet': '🌐',
  'broadband': '🌐',
  'wifi': '🌐',
  'airtel': '📱',
  'jio': '📱',
  'vi': '📱',
  'vodafone': '📱',
  'idea': '📱',
  'bsnl': '📱',
  'mtnl': '📱',
  'tata sky': '📺',
  'dish tv': '📺',
  'sun direct': '📺',
  'd2h': '📺',
  'airtel digital': '📺',
  'recharge': '📱',
  'mobile recharge': '📱',
  'dth recharge': '📺',
  'prepaid': '📱',
  'postpaid': '📱',
  
  // === ENTERTAINMENT (400+ keywords) ===
  'netflix': '🎬',
  'amazon prime': '📺',
  'prime video': '📺',
  'hotstar': '📺',
  'disney': '📺',
  'zee5': '📺',
  'sonyliv': '📺',
  'voot': '📺',
  'jiocinema': '📺',
  'aha': '📺',
  'spotify': '🎵',
  'youtube premium': '📺',
  'youtube music': '🎵',
  'apple music': '🎵',
  'gaana': '🎵',
  'jiosaavn': '🎵',
  'wynk': '🎵',
  'hungama': '🎵',
  'movie': '🎬',
  'cinema': '🎬',
  'pvr': '🎬',
  'inox': '🎬',
  'cinepolis': '🎬',
  'carnival': '🎬',
  'ticket': '🎫',
  'bookmyshow': '🎫',
  'paytm insider': '🎫',
  'concert': '🎤',
  'gaming': '🎮',
  'playstation': '🎮',
  'xbox': '🎮',
  'steam': '🎮',
  'pubg': '🎮',
  'free fire': '🎮',
  'cod': '🎮',
  'valorant': '🎮',
  
  // === HEALTH (400+ keywords) ===
  'apollo': '🏥',
  'fortis': '🏥',
  'max hospital': '🏥',
  'manipal': '🏥',
  'medanta': '🏥',
  'hospital': '🏥',
  'clinic': '🏥',
  'doctor': '👨‍⚕️',
  'dr': '👨‍⚕️',
  'medicine': '💊',
  'pharmacy': '💊',
  'chemist': '💊',
  'apollo pharmacy': '💊',
  'medplus': '💊',
  'netmeds': '💊',
  'pharmeasy': '💊',
  '1mg': '💊',
  'lab': '🧪',
  'pathology': '🧪',
  'diagnostic': '🧪',
  'lal path labs': '🧪',
  'dr lal path': '🧪',
  'thyrocare': '🧪',
  'metropolis': '🧪',
  'gym': '💪',
  'fitness': '💪',
  'cult fit': '💪',
  'cultfit': '💪',
  'gold gym': '💪',
  'talwalkars': '💪',
  'yoga': '🧘',
  'zumba': '💃',
  'physiotherapy': '🩹',
  'dental': '🦷',
  'dentist': '🦷',
  'eye': '👁️',
  'optical': '👓',
  'lenskart': '👓',
  'titan eye': '👓',
  
  // === EDUCATION (300+ keywords) ===
  'school': '🏫',
  'college': '🎓',
  'university': '🎓',
  'fees': '💰',
  'tuition': '📚',
  'coaching': '📚',
  'byju': '📱',
  'byjus': '📱',
  'unacademy': '📱',
  'vedantu': '📱',
  'physics wallah': '📱',
  'pw': '📱',
  'udemy': '💻',
  'coursera': '💻',
  'udacity': '💻',
  'khan academy': '💻',
  'skillshare': '💻',
  'textbook': '📚',
  'notebook': '📓',
  'pen': '🖊️',
  'pencil': '✏️',
  'eraser': '🧹',
  'scale': '📏',
  'compass': '📐',
  
  // === PERSONAL CARE (300+ keywords) ===
  'salon': '💇',
  'parlour': '💇',
  'spa': '💆',
  'haircut': '💈',
  'hair': '💇',
  'facial': '💆',
  'manicure': '💅',
  'pedicure': '🦶',
  'waxing': '💆',
  'massage': '💆',
  'lakme': '💄',
  'vlcc': '💆',
  'cosmetics': '💄',
  'lipstick': '💄',
  'foundation': '💄',
  'kajal': '💄',
  'eyeliner': '💄',
  'nail polish': '💅',
  'perfume': '🌸',
  'deodorant': '🌸',
  'cream': '🧴',
  'lotion': '🧴',
  'sunscreen': '🧴',
  'facewash': '🧴',
  
  // === GOVERNMENT & OFFICIAL (200+ keywords) ===
  'aadhaar': '🪪',
  'aadhar': '🪪',
  'pan': '📇',
  'pan card': '📇',
  'passport': '🛂',
  'license': '🚗',
  'driving license': '🚗',
  'dl': '🚗',
  'registration': '📋',
  'rc': '🚙',
  'vehicle registration': '🚙',
  'rto': '🚙',
  'tax': '💰',
  'gst': '💰',
  'income tax': '💰',
  'property tax': '🏠',
  'court': '⚖️',
  'legal': '⚖️',
  'notary': '📝',
  'post': '📮',
  'post office': '📮',
  'india post': '📮',
  'speed post': '📮',
  
  // === BANKING & FINANCE (300+ keywords) ===
  'sbi': '🏦',
  'hdfc': '🏦',
  'icici': '🏦',
  'axis': '🏦',
  'kotak': '🏦',
  'bank': '🏦',
  'loan': '💰',
  'emi': '💰',
  'credit card': '💳',
  'debit card': '💳',
  'atm': '🏧',
  'lic': '🛡️',
  'mutual fund': '📈',
  'sip': '📈',
  'stocks': '📊',
  'trading': '📊',
  'zerodha': '📊',
  'groww': '📈',
  'upstox': '📊',
  'paytm money': '📈',
  
  // === COMMON INDIAN NAMES (Gender Detection) ===
  'rohit': '👨',
  'rahul': '👨',
  'amit': '👨',
  'raj': '👨',
  'arjun': '👨',
  'aman': '👨',
  'aditya': '👨',
  'sanjay': '👨',
  'vikram': '👨',
  'priya': '👩',
  'anjali': '👩',
  'sneha': '👩',
  'pooja': '👩',
  'riya': '👩',
  'kavya': '👩',
  'neha': '👩',
  'deepika': '👩',
  'ananya': '👩',
  
  // === PERSON/TRANSFER INDICATORS ===
  'transfer': '💸',
  'sent': '💸',
  'received': '💰',
  'payment': '💳',
  'upi': '💳',
  'gpay': '💳',
  'google pay': '💳',
  'phonepe': '💳',
  'paytm': '💳',
  'bhim': '💳',
  'imps': '💳',
  'neft': '💳',
  'rtgs': '💳',
};

// SUBCATEGORY KEYWORD MAPPINGS (Auto-suggest subcategories)
export const SUBCATEGORY_KEYWORDS: Record<string, { category: string; subcategory: string; emoji: string }> = {
  // Transportation keywords
  'rapido': { category: 'Transportation', subcategory: 'Bike Taxi', emoji: '🏍️' },
  'ola': { category: 'Transportation', subcategory: 'Cab/Taxi', emoji: '🚕' },
  'uber': { category: 'Transportation', subcategory: 'Cab/Taxi', emoji: '🚕' },
  'auto': { category: 'Transportation', subcategory: 'Auto Rickshaw', emoji: '🛺' },
  'metro': { category: 'Transportation', subcategory: 'Metro', emoji: '🚇' },
  'train': { category: 'Transportation', subcategory: 'Train', emoji: '🚂' },
  'flight': { category: 'Transportation', subcategory: 'Flight', emoji: '✈️' },
  'petrol': { category: 'Transportation', subcategory: 'Fuel', emoji: '⛽' },
  'diesel': { category: 'Transportation', subcategory: 'Fuel', emoji: '⛽' },
  'toll': { category: 'Transportation', subcategory: 'Tolls/FASTag', emoji: '🛣️' },
  'fasttag': { category: 'Transportation', subcategory: 'Tolls/FASTag', emoji: '🛣️' },
  
  // Food keywords
  'biryani': { category: 'Food & Dining', subcategory: 'Biryani', emoji: '🍛' },
  'pizza': { category: 'Food & Dining', subcategory: 'Pizza', emoji: '🍕' },
  'burger': { category: 'Food & Dining', subcategory: 'Burger', emoji: '🍔' },
  'cafe': { category: 'Food & Dining', subcategory: 'Cafes', emoji: '☕' },
  'restaurant': { category: 'Food & Dining', subcategory: 'Restaurants', emoji: '🍽️' },
  
  // Utilities keywords
  'electricity': { category: 'Utilities', subcategory: 'Electricity', emoji: '⚡' },
  'water': { category: 'Utilities', subcategory: 'Water', emoji: '💧' },
  'gas': { category: 'Utilities', subcategory: 'Gas/LPG', emoji: '🔥' },
  'lpg': { category: 'Utilities', subcategory: 'Gas/LPG', emoji: '🔥' },
  'internet': { category: 'Utilities', subcategory: 'Internet/Broadband', emoji: '🌐' },
  'broadband': { category: 'Utilities', subcategory: 'Internet/Broadband', emoji: '🌐' },
  'mobile': { category: 'Utilities', subcategory: 'Mobile Recharge', emoji: '📱' },
  'recharge': { category: 'Utilities', subcategory: 'Mobile Recharge', emoji: '📱' },
};

export const AI_PROVIDERS = [
  {
    value: 'gemini',
    label: 'Google Gemini',
    description: '2.0 Flash - Best for receipt scanning & vision',
    free: true,
    recommended: true,
    dailyLimit: '1,500 requests/day'
  },
  {
    value: 'groq',
    label: 'Groq (Llama 3.3)',
    description: 'Lightning fast - Perfect for emoji & categorization',
    free: true,
    recommended: false,
    dailyLimit: '14,400 requests/day'
  },
  {
    value: 'local',
    label: 'Offline Mode',
    description: 'Basic keyword matching - No API required',
    free: true,
    recommended: false,
    dailyLimit: 'Unlimited'
  }
];

export const CATEGORIES = [
  'Food & Dining',
  'Transportation',
  'Utilities',
  'Entertainment',
  'Shopping',
  'Health & Fitness',
  'Groceries',
  'Income',
  'Education',
  'Personal Care',
  'Government & Official',
  'Banking & Finance',
  'Other'
];

export const DATE_RANGE_PRESETS = [
  { id: 'week', label: 'Last 7 Days', days: 7 },
  { id: 'month', label: 'Last 30 Days', days: 30 },
  { id: 'quarter', label: 'Last 90 Days', days: 90 },
  { id: 'year', label: 'Last 365 Days', days: 365 },
  { id: 'custom', label: 'Custom Range', days: 0 }
];

export const UNIT_TYPES = [
  { value: 'gram', label: 'Gram (g)' },
  { value: 'kg', label: 'Kilogram (kg)' },
  { value: 'ml', label: 'Millilitre (ml)' },
  { value: 'litre', label: 'Litre (L)' },
  { value: 'piece', label: 'Piece' },
  { value: 'packet', label: 'Packet' },
  { value: 'box', label: 'Box' },
  { value: 'other', label: 'Other' }
];

export const PERSON_TYPES = [
  { value: 'friend', label: 'Friend' },
  { value: 'family', label: 'Family' },
  { value: 'pg_owner', label: 'PG Owner' },
  { value: 'landlord', label: 'Landlord' },
  { value: 'shop_owner', label: 'Shop Owner' },
  { value: 'colleague', label: 'Colleague' },
  { value: 'other', label: 'Other' }
];

export const PROPERTY_TYPES = [
  { value: 'pg', label: 'PG/Hostel' },
  { value: 'rental', label: 'Rental House' },
  { value: 'own_house', label: 'Own House' },
  { value: 'office', label: 'Office' },
  { value: 'other', label: 'Other' }
];

export const CURRENCIES = [
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳' },
  { code: 'USD', name: 'US Dollar', symbol: '$', flag: '🇺🇸' },
  { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺' },
  { code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧' }
];

export const DEFAULT_CURRENCY = 'INR';

export const THEME_OPTIONS = [
  { value: 'light', label: 'Light' },
  { value: 'dark', label: 'Dark' },
  { value: 'system', label: 'System' }
];

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: 'LayoutDashboard' },
  { id: 'transactions', label: 'Transactions', icon: 'Receipt' },
  { id: 'products', label: 'Products', icon: 'Package' },
  { id: 'analytics', label: 'Analytics', icon: 'TrendingUp' },
  { id: 'budgets', label: 'Budgets', icon: 'Target' },
  { id: 'recurring', label: 'Recurring', icon: 'RefreshCw' },
  { id: 'add', label: 'Add Transaction', icon: 'PlusCircle' },
  { id: 'analyzer', label: 'Analyzer', icon: 'Scan' },
  { id: 'buying-list', label: 'Buying List', icon: 'ShoppingCart' },
  { id: 'export', label: 'Export', icon: 'Download' },
  { id: 'rules', label: 'Rules', icon: 'Zap' },
  { id: 'settings', label: 'Settings', icon: 'Settings' }
];

// Helper function to get emoji from category
export function getCategoryEmoji(category: Category | string): string {
  return CATEGORY_EMOJIS[category] || '📄';
}

// Helper function to get subcategory emoji
export function getSubcategoryEmoji(subcategory: string): string {
  const cleanSub = subcategory.toLowerCase().trim();
  for (const [category, subs] of Object.entries(SUBCATEGORIES)) {
    const found = subs.find(s => s.name.toLowerCase() === cleanSub);
    if (found) return found.emoji;
  }
  return '📄';
}